import bcrypt from 'bcryptjs';
import { CrossingModel } from '../models/Crossing.js';
import { IncidentModel } from '../models/Incident.js';
import { UserModel } from '../models/User.js';

export const seedDatabase = async (): Promise<void> => {
  const crossingCount = await CrossingModel.countDocuments();
  if (crossingCount === 0) {
    console.log('[Seed] Seeding initial crossings...');
    await CrossingModel.insertMany([
      {
        crossingId: 'crs-1',
        name: 'Nexus Central Urban Junction',
        type: 'urban',
        location: 'Downtown Finance District, 5th Ave & Broadway',
        status: 'optimal',
        congestionIndex: 38,
        activeVehiclesCount: 42,
        throughputPerHour: 3450,
        averageWaitTimeSeconds: 24,
        aiMode: 'adaptive',
        signalPhases: { northSouth: 'green', eastWest: 'red', timer: 45 },
        numberOfRoads: 4,
        lanesPerDirection: 4,
        incidentsCount: 0,
        weather: 'clear',
      },
      {
        crossingId: 'crs-2',
        name: 'Metro-Rail Intermodal Gate #4',
        type: 'railway',
        location: 'Industrial Freight Line, Sector 7 Crossing',
        status: 'moderate',
        congestionIndex: 65,
        activeVehiclesCount: 28,
        throughputPerHour: 1820,
        averageWaitTimeSeconds: 52,
        aiMode: 'adaptive',
        hasRailwayGate: true,
        isRailwayGateClosed: false,
        signalPhases: { northSouth: 'green', eastWest: 'red', special: 'green', timer: 30 },
        numberOfRoads: 4,
        lanesPerDirection: 2,
        incidentsCount: 1,
        weather: 'rain',
      },
      {
        crossingId: 'crs-3',
        name: 'Cyber-Express Highway Toll Plaza',
        type: 'highway_toll',
        location: 'Interstate 95 Nexa Expressway Milestone 140',
        status: 'heavy_congestion',
        congestionIndex: 88,
        activeVehiclesCount: 115,
        throughputPerHour: 8900,
        averageWaitTimeSeconds: 78,
        aiMode: 'surge_mitigation',
        signalPhases: { northSouth: 'green', eastWest: 'green', timer: 90 },
        numberOfRoads: 4,
        lanesPerDirection: 8,
        incidentsCount: 2,
        weather: 'fog',
      },
      {
        crossingId: 'crs-4',
        name: 'Apex International Border Portal',
        type: 'border',
        location: 'Northern Frontier Checkpoint Alpha',
        status: 'moderate',
        congestionIndex: 54,
        activeVehiclesCount: 36,
        throughputPerHour: 950,
        averageWaitTimeSeconds: 140,
        aiMode: 'fixed',
        hasBorderGate: true,
        isBorderGateOpen: true,
        signalPhases: { northSouth: 'yellow', eastWest: 'red', special: 'green', timer: 15 },
        numberOfRoads: 4,
        lanesPerDirection: 3,
        incidentsCount: 0,
        weather: 'snow',
      },
      {
        crossingId: 'crs-5',
        name: 'Bay-Bridge Drawbridge Crossing',
        type: 'drawbridge',
        location: 'Harbor Channel Suspension Link',
        status: 'optimal',
        congestionIndex: 22,
        activeVehiclesCount: 18,
        throughputPerHour: 2200,
        averageWaitTimeSeconds: 15,
        aiMode: 'adaptive',
        hasDrawbridge: true,
        isDrawbridgeUp: false,
        signalPhases: { northSouth: 'green', eastWest: 'red', special: 'green', timer: 60 },
        numberOfRoads: 4,
        lanesPerDirection: 3,
        incidentsCount: 0,
        weather: 'clear',
      },
      {
        crossingId: 'crs-6',
        name: 'Eco-Industrial Logistics Node',
        type: 'logistics',
        location: 'Nexa Automated Port & Shipping Hub',
        status: 'optimal',
        congestionIndex: 31,
        activeVehiclesCount: 25,
        throughputPerHour: 4100,
        averageWaitTimeSeconds: 18,
        aiMode: 'adaptive',
        signalPhases: { northSouth: 'red', eastWest: 'green', timer: 25 },
        numberOfRoads: 4,
        lanesPerDirection: 3,
        incidentsCount: 0,
        weather: 'clear',
      },
      {
        crossingId: 'crs-7',
        name: 'Starlight School Safety Corridor',
        type: 'school',
        location: 'Oakwood Residential District',
        status: 'optimal',
        congestionIndex: 19,
        activeVehiclesCount: 12,
        throughputPerHour: 1200,
        averageWaitTimeSeconds: 10,
        aiMode: 'adaptive',
        signalPhases: { northSouth: 'green', eastWest: 'red', timer: 40 },
        numberOfRoads: 4,
        lanesPerDirection: 2,
        incidentsCount: 0,
        weather: 'clear',
      },
      {
        crossingId: 'crs-8',
        name: 'Aerotropolis Airport Link Interchange',
        type: 'airport',
        location: 'International Terminal 3 Access Flyover',
        status: 'heavy_congestion',
        congestionIndex: 82,
        activeVehiclesCount: 94,
        throughputPerHour: 7400,
        averageWaitTimeSeconds: 65,
        aiMode: 'surge_mitigation',
        signalPhases: { northSouth: 'green', eastWest: 'red', timer: 20 },
        numberOfRoads: 4,
        lanesPerDirection: 5,
        incidentsCount: 1,
        weather: 'rain',
      },
    ]);
  }

  const incidentCount = await IncidentModel.countDocuments();
  if (incidentCount === 0) {
    console.log('[Seed] Seeding initial incidents...');
    await IncidentModel.insertMany([
      {
        incidentId: 'inc-101',
        crossingId: 'crs-3',
        crossingName: 'Cyber-Express Highway Toll Plaza',
        title: 'Stalled Freight Container Truck in Lane 4',
        type: 'VEHICLE_BREAKDOWN',
        severity: 'critical',
        timestamp: new Date(Date.now() - 600000),
        status: 'dispatching',
        description: 'An eighteen-wheeler carrying sensitive cargo has suffered air-brake lockup right before Toll Gate 4. Causing a 1.2-mile backup.',
        assignedTeam: 'Heavy Wrecker Tow Unit #7',
        detectionSource: 'AUTOMATED_TELEMETRY_ENGINE',
      },
      {
        incidentId: 'inc-102',
        crossingId: 'crs-8',
        crossingName: 'Aerotropolis Airport Link Interchange',
        title: 'Minor Rear-End Collision near Terminal Offramp',
        type: 'COLLISION',
        severity: 'medium',
        timestamp: new Date(Date.now() - 1500000),
        status: 'resolving',
        description: 'Two rideshare vehicles collided during an abrupt lane merge. Passengers are safe, vehicles being cleared to shoulder.',
        assignedTeam: 'Highway Patrol Cruiser #44',
        detectionSource: 'CAMERA_ALPR_AI',
      },
      {
        incidentId: 'inc-103',
        crossingId: 'crs-2',
        crossingName: 'Metro-Rail Intermodal Gate #4',
        title: 'Acoustic Sensor False Alarm Trigger',
        type: 'SENSOR_ANOMALY',
        severity: 'low',
        timestamp: new Date(Date.now() - 2500000),
        status: 'active',
        description: 'Heavy rainfall is causing intermittent acoustic sensor pings on Railway Gate #4. Automated diagnostic sweep initiated.',
        detectionSource: 'AUTOMATED_TELEMETRY_ENGINE',
      },
    ]);
  }

  const userCount = await UserModel.countDocuments();
  if (userCount === 0) {
    console.log('[Seed] Seeding default RBAC users...');
    const hashedPass = await bcrypt.hash('admin123', 10);
    await UserModel.insertMany([
      {
        name: 'Command Centre Super Admin',
        email: 'admin@omnicross.city',
        passwordHash: hashedPass,
        role: 'SUPER_ADMIN',
      },
      {
        name: 'City Operations Director',
        email: 'cityadmin@omnicross.city',
        passwordHash: hashedPass,
        role: 'CITY_ADMIN',
      },
      {
        name: 'Chief Traffic Operator',
        email: 'operator@omnicross.city',
        passwordHash: hashedPass,
        role: 'TRAFFIC_OPERATOR',
      },
      {
        name: 'EMS Commander',
        email: 'emergency@omnicross.city',
        passwordHash: hashedPass,
        role: 'EMERGENCY_OPERATOR',
      },
      {
        name: 'Traffic Analyst',
        email: 'analyst@omnicross.city',
        passwordHash: hashedPass,
        role: 'ANALYST',
      },
      {
        name: 'Public Viewer',
        email: 'viewer@omnicross.city',
        passwordHash: hashedPass,
        role: 'VIEWER',
      },
    ]);
  }
};
