import { Crossing, Incident, InfrastructureNode, AlprRecord, ThroughputDataPoint, CategoryDataPoint } from './types';

export const INITIAL_CROSSINGS: Crossing[] = [
  {
    id: 'crs-1',
    name: 'Nexus Central Urban Junction',
    type: 'urban',
    location: 'Downtown Finance District, 5th Ave & Broadway',
    status: 'optimal',
    congestionIndex: 38,
    activeVehiclesCount: 42,
    throughputPerHour: 3450,
    averageWaitTimeSeconds: 24,
    aiMode: 'adaptive',
    signalPhases: {
      northSouth: 'green',
      eastWest: 'red',
      timer: 45,
    },
    lanesPerDirection: 4,
    incidentsCount: 0,
    weather: 'clear',
  },
  {
    id: 'crs-2',
    name: 'Metro-Rail Intermodal Gate #4',
    type: 'railway',
    location: 'Industrial Freight Line, Sector 7 Crossing',
    status: 'moderate',
    congestionIndex: 65,
    activeVehiclesCount: 28,
    throughputPerHour: 1820,
    averageWaitTimeSeconds: 52,
    aiMode: 'adaptive',
    hasRailwayGate: true,
    isRailwayGateClosed: false,
    signalPhases: {
      northSouth: 'green',
      eastWest: 'red',
      special: 'green',
      timer: 30,
    },
    lanesPerDirection: 2,
    incidentsCount: 1,
    weather: 'rain',
  },
  {
    id: 'crs-3',
    name: 'Cyber-Express Highway Toll Plaza',
    type: 'highway_toll',
    location: 'Interstate 95 Nexa Expressway Milestone 140',
    status: 'heavy_congestion',
    congestionIndex: 88,
    activeVehiclesCount: 115,
    throughputPerHour: 8900,
    averageWaitTimeSeconds: 78,
    aiMode: 'surge_mitigation',
    signalPhases: {
      northSouth: 'green',
      eastWest: 'green',
      timer: 90,
    },
    lanesPerDirection: 8,
    incidentsCount: 2,
    weather: 'fog',
  },
  {
    id: 'crs-4',
    name: 'Apex International Border Portal',
    type: 'border',
    location: 'Northern Frontier Checkpoint Alpha',
    status: 'moderate',
    congestionIndex: 54,
    activeVehiclesCount: 36,
    throughputPerHour: 950,
    averageWaitTimeSeconds: 140,
    aiMode: 'fixed',
    hasBorderGate: true,
    isBorderGateOpen: true,
    signalPhases: {
      northSouth: 'yellow',
      eastWest: 'red',
      special: 'green',
      timer: 15,
    },
    lanesPerDirection: 3,
    incidentsCount: 0,
    weather: 'snow',
  },
  {
    id: 'crs-5',
    name: 'Bay-Bridge Drawbridge Crossing',
    type: 'drawbridge',
    location: 'Harbor Channel Suspension Link',
    status: 'optimal',
    congestionIndex: 22,
    activeVehiclesCount: 18,
    throughputPerHour: 2200,
    averageWaitTimeSeconds: 15,
    aiMode: 'adaptive',
    hasDrawbridge: true,
    isDrawbridgeUp: false,
    signalPhases: {
      northSouth: 'green',
      eastWest: 'red',
      special: 'green',
      timer: 60,
    },
    lanesPerDirection: 3,
    incidentsCount: 0,
    weather: 'clear',
  },
  {
    id: 'crs-6',
    name: 'Eco-Industrial Logistics Node',
    type: 'logistics',
    location: 'Nexa Automated Port & Shipping Hub',
    status: 'optimal',
    congestionIndex: 31,
    activeVehiclesCount: 25,
    throughputPerHour: 4100,
    averageWaitTimeSeconds: 18,
    aiMode: 'adaptive',
    signalPhases: {
      northSouth: 'red',
      eastWest: 'green',
      timer: 25,
    },
    lanesPerDirection: 3,
    incidentsCount: 0,
    weather: 'clear',
  },
  {
    id: 'crs-7',
    name: 'Starlight School Safety Corridor',
    type: 'school',
    location: 'Oakwood Residential District',
    status: 'optimal',
    congestionIndex: 19,
    activeVehiclesCount: 12,
    throughputPerHour: 1200,
    averageWaitTimeSeconds: 10,
    aiMode: 'adaptive',
    signalPhases: {
      northSouth: 'green',
      eastWest: 'red',
      timer: 40,
    },
    lanesPerDirection: 2,
    incidentsCount: 0,
    weather: 'clear',
  },
  {
    id: 'crs-8',
    name: 'Aerotropolis Airport Link Interchange',
    type: 'airport',
    location: 'International Terminal 3 Access Flyover',
    status: 'heavy_congestion',
    congestionIndex: 82,
    activeVehiclesCount: 94,
    throughputPerHour: 7400,
    averageWaitTimeSeconds: 65,
    aiMode: 'surge_mitigation',
    signalPhases: {
      northSouth: 'green',
      eastWest: 'red',
      timer: 20,
    },
    lanesPerDirection: 5,
    incidentsCount: 1,
    weather: 'rain',
  },
];

export const INITIAL_INCIDENTS: Incident[] = [
  {
    id: 'inc-101',
    crossingId: 'crs-3',
    crossingName: 'Cyber-Express Highway Toll Plaza',
    title: 'Stalled Freight Container Truck in Lane 4',
    severity: 'critical',
    timestamp: '10 mins ago',
    status: 'dispatching',
    description: 'An eighteen-wheeler carrying sensitive cargo has suffered air-brake lockup right before Toll Gate 4. Causing a 1.2-mile backup.',
    responderAssigned: 'Heavy Wrecker Tow Unit #7',
  },
  {
    id: 'inc-102',
    crossingId: 'crs-8',
    crossingName: 'Aerotropolis Airport Link Interchange',
    title: 'Minor Rear-End Collision near Terminal Offramp',
    severity: 'medium',
    timestamp: '25 mins ago',
    status: 'resolving',
    description: 'Two rideshare vehicles collided during an abrupt lane merge. Passengers are safe, vehicles being cleared to shoulder.',
    responderAssigned: 'Highway Patrol Cruiser #44',
  },
  {
    id: 'inc-103',
    crossingId: 'crs-2',
    crossingName: 'Metro-Rail Intermodal Gate #4',
    title: 'Acoustic Sensor False Alarm Trigger',
    severity: 'low',
    timestamp: '42 mins ago',
    status: 'active',
    description: 'Heavy rainfall is causing intermittent acoustic sensor pings on Railway Gate #4. Automated diagnostic sweep initiated.',
  },
];

export const INITIAL_INFRASTRUCTURE: InfrastructureNode[] = [
  {
    id: 'node-us-east',
    region: 'US-East (N. Virginia)',
    nodeName: 'Edge-Core-Alpha-01',
    status: 'healthy',
    cpuUsage: 42,
    memoryUsage: 58,
    requestsPerSecond: 18400,
    websocketConnections: 125000,
    edgeLatencyMs: 14,
    activeWorkers: 32,
  },
  {
    id: 'node-eu-central',
    region: 'EU-Central (Frankfurt)',
    nodeName: 'Edge-Core-Beta-04',
    status: 'healthy',
    cpuUsage: 68,
    memoryUsage: 72,
    requestsPerSecond: 24100,
    websocketConnections: 189000,
    edgeLatencyMs: 18,
    activeWorkers: 48,
  },
  {
    id: 'node-ap-south',
    region: 'AP-South (Mumbai)',
    nodeName: 'Edge-Core-Gamma-09',
    status: 'scaling',
    cpuUsage: 89,
    memoryUsage: 84,
    requestsPerSecond: 41200,
    websocketConnections: 290000,
    edgeLatencyMs: 29,
    activeWorkers: 64,
  },
  {
    id: 'node-ap-northeast',
    region: 'AP-NorthEast (Tokyo)',
    nodeName: 'Edge-Core-Delta-02',
    status: 'healthy',
    cpuUsage: 35,
    memoryUsage: 45,
    requestsPerSecond: 12300,
    websocketConnections: 95000,
    edgeLatencyMs: 12,
    activeWorkers: 24,
  },
];

export const INITIAL_ALPR_RECORDS: AlprRecord[] = [
  {
    id: 'alpr-901',
    timestamp: '14:23:01',
    crossingName: 'Apex International Border Portal',
    plate: 'NEX-7729',
    vehicleType: 'Heavy Cargo Transport',
    speed: 18,
    flagged: false,
  },
  {
    id: 'alpr-902',
    timestamp: '14:22:54',
    crossingName: 'Nexus Central Urban Junction',
    plate: 'VIP-0001',
    vehicleType: 'Armored State Escort',
    speed: 48,
    flagged: true,
    flagReason: 'Active VIP Green Corridor Priority',
  },
  {
    id: 'alpr-903',
    timestamp: '14:22:15',
    crossingName: 'Cyber-Express Highway Toll Plaza',
    plate: 'HAZ-3984',
    vehicleType: 'Chemical Tanker Truck',
    speed: 62,
    flagged: false,
  },
  {
    id: 'alpr-904',
    timestamp: '14:21:40',
    crossingName: 'Bay-Bridge Drawbridge Crossing',
    plate: 'EVX-9921',
    vehicleType: 'Electric Autonomous Cab',
    speed: 35,
    flagged: false,
  },
  {
    id: 'alpr-905',
    timestamp: '14:20:12',
    crossingName: 'Cyber-Express Highway Toll Plaza',
    plate: 'STN-8812',
    vehicleType: 'Sport Coupe',
    speed: 89,
    flagged: true,
    flagReason: 'Excessive Speed Enforcement Flag',
  },
];

export const THROUGHPUT_HISTORY: ThroughputDataPoint[] = [
  { time: '08:00', actualThroughput: 14200, aiPredictedCapacity: 15000, congestionLevel: 35 },
  { time: '09:00', actualThroughput: 28500, aiPredictedCapacity: 29000, congestionLevel: 82 },
  { time: '10:00', actualThroughput: 24100, aiPredictedCapacity: 26000, congestionLevel: 68 },
  { time: '11:00', actualThroughput: 19800, aiPredictedCapacity: 22000, congestionLevel: 45 },
  { time: '12:00', actualThroughput: 22300, aiPredictedCapacity: 24000, congestionLevel: 60 },
  { time: '13:00', actualThroughput: 23900, aiPredictedCapacity: 25000, congestionLevel: 65 },
  { time: '14:00', actualThroughput: 31200, aiPredictedCapacity: 33000, congestionLevel: 88 },
  { time: '15:00', actualThroughput: 29800, aiPredictedCapacity: 31000, congestionLevel: 75 },
];

export const VEHICLE_CATEGORIES: CategoryDataPoint[] = [
  { name: 'Commuter Sedans & SUVs', value: 48, color: '#6366f1' },
  { name: 'Heavy Trucks & Freight', value: 22, color: '#f59e0b' },
  { name: 'Public Transit & Trains', value: 14, color: '#10b981' },
  { name: 'Electric Vehicles (EV)', value: 11, color: '#06b6d4' },
  { name: 'Emergency & VIP', value: 5, color: '#ef4444' },
];
